sudo: required
service:
  - docker

before_install: 
  - docker build -t shayunited21/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shayunited21/react-test npm test -- --coverage

after_success: 
  - docker build -t shayunited21/multi-client ./client
  - docker build -t shayunited21/multi-nginx ./nginx
  - docker build -t shayunited21/multi-worker ./worker
  - docker build -t shayunited21/multi-server ./server
# login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push to docker hub
  - docker push shayunited21/multi-client 
  - docker push shayunited21/multi-nginx 
  - docker push shayunited21/multi-worker 
  - docker push shayunited21/multi-server 

deploy:
 provider: elasticbeanstalk
 region: 'us-east-2'
 app: 'multi-docker'
 env: 'Multi-docker-env'
 bucket_name: 'elasticbeanstalk-us-east-2-349703987105'
 bucket_path: 'docker-multi'
 on:
   branch: main
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
