version: "3"
services:
 client:
   image: "shayunited21/multi-client"
   mem_limit: 128m
   hostname: client
 server:
   image: "shayunited21/multi-server"
   mem_limit: 128m
   hostname: api
   environment:
     - REDIS_HOST=$REDIS_HOST
     - REDIS_PORT=$REDIS_PORT
     - PGUSER=$PGUSER
     - PGHOST=$PGHOST
     - PGDATABASE=$PGDATABASE
     - PGPASSWORD=$PGPASSWORD
     - PGPORT=$PGPORT
 worker:
   image: "shayunited21/multi-worker"
   mem_limit: 128m
   hostname: worker
   environment:
     - REDIS_HOST=$REDIS_HOST
     - REDIS_PORT=$REDIS_PORT
 nginx:
   image: "shayunited21/multi-nginx"
   mem_limit: 128m
   hostname: nginx
   ports:
     - "80:80"